plugin.plugin_configuration.facets_processor.facets_custom_label:
  type: mapping
  label: 'Settings for the facets_custom_label processor'
  mapping:
    replacement_values:
      type: text
      label: 'Replacement values'
